#variable "subnet_id" {}
variable "db_subnet_group_name" {}
variable "subnet_id_az1" {}
variable "subnet_group_tag" {}
variable "allocated_storage" {}
variable "engine" {}
variable "engine_version" {}
variable "instance_class" {}
variable "db_name" {}
variable "username" {}
variable "password" {}
variable "skip_final_snapshot" {}